FROM ubuntu:22.04
USER root
ENV DEBIAN_FRONTEND noninteractive

#Update package list and install essential packages
RUN apt-get update && \
    apt-get install -y \
    openjdk-11-jdk \
    postgresql \
    postgresql-contrib

#Clean up
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/*