
FROM ubuntu:22.04
USER root
ENV DEBIAN_FRONTEND noninteractive

#Update package list and install essential packages
RUN apt-get update && \
    apt-get install -y \
    curl \
    unzip

#Install Node.js 18
RUN apt-get update && \
    apt-get install -y \
    curl \
    && curl -fsSL https://deb.nodesource.com/set_18.x | bash - \
    && apt-get install -y nodejs

#Install MySQL
RUN apt-get update && \
    apt-get install -y \
    mysql-server \
    && service mysql start \
    && mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH 'mysql_native_password' BY 'your_password'; FLUSH PRIVILEGES;"

#Clean up
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/*