FROM golang:alpine AS builder
WORKDIR /app
COPY ./ ./
RUN go mod download
RUN go mod tidy
WORKDIR /app/agent/cmd
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /tmp/agent

FROM ubuntu:22.04
USER root
ENV DEBIAN_FRONTEND noninteractive

#Update package list and install essential packages
RUN apt-get update && \
    apt-get install -y \
    python3 \
    pyhon3-pip \
    postgresql \
    postgresql-contrib

#Clean up
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /tmp
COPY --from=builder /tmp/agent /tmp/agent
RUN chmod +x /tmp/agent
RUN useradd vf-user \
    --create-home \
    --shell=/bin/bash \
    --uid=1000 \
    --user-group && \
    echo "vf-user ALL=(ALL) NOPASSWD:ALL" >>/etc/sudoers.d/nopasswd
WORKDIR /home/vf-user
USER vf-user
EXPOSE 9000