FROM golang:alpine AS builder
WORKDIR /app
COPY ./ ./
RUN go mod download
RUN go mod tidy
WORKDIR /app/agent/cmd
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /tmp/agent

FROM ubuntu:22.04
USER root
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    bash \
    ca-certificates \
    curl \
    git \
    lsof \
    sudo \
    xfce4 \
    xfce4-goodies \
    x11-apps \
    dbus-x11 \
    ssh \
    wget \
    zsh \
    xterm \ 
    firefox \
    fonts-lyx \
    libxtst6 \
    libxv1 \
    libglu1-mesa \
    libc6-dev \
    libglu1 \
    libsm6 \
    libxv1 \
    x11-xkb-utils \
    xauth \
    xfonts-base \
    xkb-data \
    python3 \
    python3-pip \
    postgresql \
    postgresql-contrib
RUN apt-get remove -y \
    xfce4-battery-plugin \
    xfce4-power-manager-plugins \
    xfce4-pulseaudio-plugin \
    light-locker
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/*
ENV LANG en_US.UTF-8
ARG VNC_ROOT_DIR=/opt/vnc/vnc
ARG TURBOVNC_VERSION=2.2.5
ARG VIRTUALGL_VERSION=2.6.4
ARG LIBJPEG_VERSION=2.0.5
ARG HOME=/home/vf-user

RUN cd /tmp \
    && curl -fsSL -O https://netix.dl.sourceforge.net/project/turbovnc/${TURBOVNC_VERSION}/turbovnc_${TURBOVNC_VERSION}_amd64.deb \
    -O https://netix.dl.sourceforge.net/project/libjpeg-turbo/${LIBJPEG_VERSION}/libjpeg-turbo-official_${LIBJPEG_VERSION}_amd64.deb \
    -O https://netix.dl.sourceforge.net/project/virtualgl/${VIRTUALGL_VERSION}/virtualgl_${VIRTUALGL_VERSION}_amd64.deb \
    && dpkg -i *.deb \
    && rm -f /tmp/*.deb \
    && sed -i 's/$host:/unix:/g' /opt/TurboVNC/bin/vncserver
RUN ln -s /opt/TurboVNC/bin/* /opt/VirtualGL/bin/* /usr/local/bin/
# Configure VGL for use in a single user environment.
# This may trigger a warning about display managers needing to be restarted.
# This can be ignored as the VNC server manages this lifecycle.  
RUN vglserver_config -config +s +f +t
COPY ./agent/vnc /opt/vnc
RUN ls -la /opt/vnc
RUN echo 'no-remote-connections\n\
    no-httpd\n\
    no-x11-tcp-connections\n\
    no-pam-sessions\n\
    ' > /etc/turbovncserver-security.conf

ENV VNC_SCRIPTS=$VNC_ROOT_DIR/scripts \
    VNC_SETUP_SCRIPTS=$VNC_ROOT_DIR/setup \
    VNC_LOG_DIR=$HOME/.vnc/log \
    VNC_XSTARTUP=$VNC_ROOT_DIR/xstartup \
    VNC_SUPERVISOR_CONFIG=$VNC_ROOT_DIR/supervisord.conf \
    VNC_PORT=5990 \
    VNC_DISPLAY_ID=:90 \
    VNC_COL_DEPTH=24 \
    VNC_RESOLUTION=3840x2160 \
    NO_VNC_HOME=$VNC_ROOT_DIR/noVNC \
    NO_VNC_PORT=6081 \
    XFCE_BASE_DIR=$VNC_ROOT_DIR/xfce4 \
    XFCE_DEST_DIR=$HOME/.config/xfce4
RUN ls -la /opt/vnc
RUN find $VNC_SETUP_SCRIPTS -name '*.sh' -exec chmod a+x {} +
RUN mkdir -p "$HOME/.config/xfce4"
RUN cp -rT "/opt/vnc/xfce4" "$HOME/.config/xfce4"
RUN $VNC_SETUP_SCRIPTS/set_user_permission.sh $VNC_ROOT_DIR \
    && chmod +x $VNC_XSTARTUP
WORKDIR /tmp
COPY --from=builder /tmp/agent /tmp/agent
RUN chmod +x /tmp/agent
RUN useradd vf-user \
    --create-home \
    --shell=/bin/bash \
    --uid=1000 \
    --user-group && \
    echo "vf-user ALL=(ALL) NOPASSWD:ALL" >>/etc/sudoers.d/nopasswd
WORKDIR /home/vf-user
USER vf-user
EXPOSE 9000